name: dart_redact_cli
description: Command line interface for DartRedact.
version: 0.1.0
environment:
  sdk: ^3.4.0
dependencies:
  dart_redact_core:
    path: ../dart_redact_core
  dart_redact_detectors:
    path: ../dart_redact_detectors
dev_dependencies:
  test: ^1.25.0
